// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package user

// Define an input type for the mutation below.
// https://graphql.org/learn/schema/#input-types
type CreateUserInput struct {
	// User name
	Name string `json:"name"`
	// User age
	Age int `json:"age"`
}

// Define an input type for the mutation below.
// https://graphql.org/learn/schema/#input-types
type FollowUserInput struct {
	// ID of the following User
	UserID int `json:"userID"`
	// ID of Followed User
	FollowUserID int `json:"followUserID"`
}
